### PR TITLE
Support KEYS_ONLY global secondary indexes

### PR DESCRIPTION
**Pull request by killergerbah**
Fixes https://github.com/N3TWORK/dynamap/issues/65

### CODE REVIEW

**Comment by TheEnigmaThatIsMe** [comment]
What problem is this change solving?

**Review by vazor-n3twork — APPROVED** [review]
Nothing jumping out as a problem for me after a quick scan. Nice work!

**Review by nanreh — APPROVED** [review]
Looks good!

**Review by TheEnigmaThatIsMe — APPROVED** [review]

**Comment by killergerbah** [comment]
> What problem is this change solving?

To give more context around the ticket, it was not possible to create GSIs with a `KEYS_ONLY` projection type using configuration like this:
```      
"globalSecondaryIndexes": [
        {
          "index": "MissionCreatedIndex",
          "hashKey": "playerId",
          "rangeKey": "created",
          "projectionType": "KEYS_ONLY"
        },
        ...
]
```
Yesterday I ran into a case where I really wanted to do that to save cost on DynamoDB writes, and so needed this fix.

**Pull request merged**
